version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-pos
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:mysql://db:3306/jsppos
      - DB_USERNAME=root
      - DB_PASSWORD=rootroot
    depends_on:
      - db
  db:
    build:
      context: .
      dockerfile: Dockerfile-database
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_DATABASE: jsppos
    ports:
      - "3306:3306"
